apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nc
  namespace: test
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
            - {key: kubernetes.io/metadata.name, operator: NotIn, values: [default]}
